import type { NextPage } from 'next'
import Head from 'next/head'
import { Layout, PageHeader } from 'antd'

import { Footer as CustomFooter, SearchWords } from '../components'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Словарь</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Layout>
        <PageHeader title="Словарь" />
        <Layout.Content>
          <SearchWords />
        </Layout.Content>

        <Layout.Footer>
          <CustomFooter />
        </Layout.Footer>
      </Layout>
    </>
  )
}

export default Home
