import { useEffect, useState } from 'react'
import type { NextPage } from 'next'
import Head from 'next/head'

import { Input, Space } from 'antd'

import { Footer } from '../components'

import styles from '../styles/Home.module.css'

const { Search } = Input

type WordProps = {
  _id: string
  __v: number
  translations: string[]
  word: string
  synonyms: string[]
  examples: {
    text: string
    source: string
  }
}

const Word = (props: Partial<WordProps>) => {
  return (
    <div className="word">
      <div className="wordSource">{props.word}</div>
    </div>
  )
}

const Home: NextPage = () => {
  const onSearch = (query) => {
    console.log('query: ', query) // eslint-disable-line
  }

  const [words, setWords] = useState<Partial<WordProps>[]>([])

  useEffect(() => {
    ;(async () => {
      let response = await fetch('/api/words', {
        headers: {
          'Content-type': 'application/json; charset=UTF-8',
          Accept: 'application/json',
        },
      })

      let { result } = await response.json()

      setWords(result)
    })()
  }, [])

  return (
    <div className={styles.container}>
      <Head>
        <title>Словарь</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Space direction="vertical">
          <Search
            placeholder="введите слово"
            enterButton="Найти!"
            size="large"
            onSearch={onSearch}
          />
        </Space>

        <Space direction="vertical">
          {words.map((wordItem) => (
            <Word word={wordItem.word} key={wordItem?._id} />
          ))}
        </Space>
      </main>

      <Footer />
    </div>
  )
}

export default Home
